from typing import Dict, Any
import os,json
def cat_input_from_md(inputs: Dict[str, Any],folder_path: str="inputs")->Dict[str, Any]:
    for md_file in os.listdir(folder_path):
        if not md_file.endswith(".md"):
            continue
        with open(os.path.join(folder_path, md_file), 'r', encoding='utf-8') as file:
            content = file.read()
            file_property = md_file[:-3]
            inputs[file_property] = content
    return inputs
class PaperWriterState:
    """
    论文生成状态管理器 (State Machine Context)
    用于在整个 Agentic Workflow 的各个节点之间传递、更新和保存上下文数据。
    """

    def __init__(self, inputs: Dict[str, Any],input_from_md:bool=True):
        # ==========================================
        # 1. 初始输入素材 (Initial Inputs)
        # ==========================================
        if input_from_md:
            inputs = cat_input_from_md(inputs)
        self.model: str = inputs.get("model", "gemini-3-pro")
        self.topic: str = inputs.get("topic", "")
        self.existing_sections: str = inputs.get("existing_sections", "无")
        self.existing_material: str = inputs.get("existing_material", "无")
        self.research_gaps: str = inputs.get("research_gaps", "")
        self.journal_style: str = inputs.get("journal_style", "Nature/Science 子刊级别的冷峻、客观风格")
        self.language: str = inputs.get("language", "English")
        self.user_requirements: str = inputs.get("user_requirements", "")

        # ==========================================
        # 2. 全局架构数据 (Generated by Node 1: Architect)
        # ==========================================
        self.domain: str = ""  # 识别出的确切研究领域
        self.outline: str = ""  # 完整论文大纲 (IMRaD结构)
        self.gaps_and_contributions: str = ""  # 文献空白与本研究贡献的严密映射

        # ==========================================
        # 3. 循环控制与过程状态 (Loop & Process State)
        # ==========================================
        # 存储已完成/审核通过的章节
        self.completed_sections = []
    # ==========================================
    # 辅助方法 (Helper Methods)
    # ==========================================
    def get_sections_keys(self) -> str:
        """
        获取已完成章节的名称列表 (例如: "1. Introduction, 2. Methods")
        用于在 Prompt 中告诉模型目前写了哪些章节。
        """
        if not self.sections:
            return "目前暂无已完成的章节。"
        return ", ".join(list(self.sections.keys()))

    def get_sections_text(self) -> str:
        """
        获取所有已完成章节的合并文本，作为撰写下一节的上下文依据。
        """
        if not self.sections:
            return "无前文参考。"

        text_blocks = []
        for title, content in self.sections.items():
            text_blocks.append(f"## {title}\n{content}")
        return "\n\n".join(text_blocks)

    def save_current_section(self):
        """
        核心动作：当当前章节在 Node 5 (Judge) 被判定为 'done' 时，
        调用此方法将其归档到 sections 字典中，并清理当前草稿。
        """
        section_name = self.current_plan.get("section_to_write")
        if section_name and self.current_section_content:
            self.sections[section_name] = self.current_section_content
            print(f"📁 章节 [{section_name}] 审核通过，已成功归档至状态池。")

            # 清空当前草稿与计划，为规划下一节做准备
            self.current_section_content = ""
            self.current_plan = {}

    def export_checkpoint(self) -> Dict[str, Any]:
        """
        将当前状态导出为字典（可配合 json.dump 保存为本地 checkpoint 文件），
        极其适合长耗时任务的断点续传机制。
        """
        return self.__dict__

    def get_prompt_language(self) -> str:
        """
        根据当前语言设置，返回提示词的语言版本
        返回 'zh' 表示中文提示词，'en' 表示英文提示词
        """
        return 'zh' if self.language.strip() == '中文' else 'en'
